
# print('scope: ',self.scope)
sc = {
    "type": "websocket",
    "path": "/websocket/13",
    "raw_path": b"/websocket/13",
    "root_path": "",
    "headers": [
        (b"host", b"127.0.0.1:8000"),
        (b"connection", b"Upgrade"),
        (b"pragma", b"no-cache"),
        (b"cache-control", b"no-cache"),
        (
            b"user-agent",
            b"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
        ),
        (b"upgrade", b"websocket"),
        (b"origin", b"http://127.0.0.1:8000"),
        (b"sec-websocket-version", b"13"),
        (b"accept-encoding", b"gzip, deflate, br, zstd"),
        (b"accept-language", b"en-US,en;q=0.9"),
        (
            b"cookie",
            b"csrftoken=convhsD4WEkQwLgz5U6MxTmrRhDwlGjx; sessionid=6hhimjuz4rj3zq5u74mosu4pli4jtvi7",
        ),
        (b"sec-websocket-key", b"0nJv8FtrnWOKO5v0wiA9Xg=="),
        (b"sec-websocket-extensions", b"permessage-deflate; client_max_window_bits"),
    ],
    "query_string": b"",
    "client": ["127.0.0.1", 39650],
    "server": ["127.0.0.1", 8000],
    "subprotocols": [],
    "asgi": {"version": "3.0"},
    "cookies": {
        "csrftoken": "convhsD4WEkQwLgz5U6MxTmrRhDwlGjx",
        "sessionid": "6hhimjuz4rj3zq5u74mosu4pli4jtvi7",
    },
    "session": "<django.utils.functional.LazyObject object at 0x773a8abbbef0>, 'user': <channels.auth.UserLazyObject object at 0x773a8abb9100>",
    "path_remaining": "",
    "url_route": {"args": (), "kwargs": {"id": 13}},
}

# print(dir(request.user)) in class Main
re = [
    "__class__",
    "__delattr__",
    "__dict__",
    "__dir__",
    "__doc__",
    "__eq__",
    "__format__",
    "__ge__",
    "__getattribute__",
    "__getstate__",
    "__gt__",
    "__hash__",
    "__init__",
    "__init_subclass__",
    "__int__",
    "__le__",
    "__lt__",
    "__module__",
    "__ne__",
    "__new__",
    "__reduce__",
    "__reduce_ex__",
    "__repr__",
    "__setattr__",
    "__sizeof__",
    "__str__",
    "__subclasshook__",
    "__weakref__",
    "_groups",
    "_user_permissions",
    "check_password",
    "delete",
    "get_all_permissions",
    "get_group_permissions",
    "get_user_permissions",
    "get_username",
    "groups",
    "has_module_perms",
    "has_perm",
    "has_perms",
    "id",
    "is_active",
    "is_anonymous",
    "is_authenticated",
    "is_staff",
    "is_superuser",
    "pk",
    "save",
    "set_password",
    "user_permissions",
    "username",
]
# print(dir(request.user)) Home view
b = [
    "DoesNotExist",
    "EMAIL_FIELD",
    "Meta",
    "MultipleObjectsReturned",
    "REQUIRED_FIELDS",
    "USERNAME_FIELD",
    "__class__",
    "__delattr__",
    "__dict__",
    "__dir__",
    "__doc__",
    "__eq__",
    "__format__",
    "__ge__",
    "__getattribute__",
    "__getstate__",
    "__gt__",
    "__hash__",
    "__init__",
    "__init_subclass__",
    "__le__",
    "__lt__",
    "__module__",
    "__ne__",
    "__new__",
    "__reduce__",
    "__reduce_ex__",
    "__repr__",
    "__setattr__",
    "__setstate__",
    "__sizeof__",
    "__str__",
    "__subclasshook__",
    "__weakref__",
    "_check_column_name_clashes",
    "_check_constraints",
    "_check_db_table_comment",
    "_check_default_pk",
    "_check_field_name_clashes",
    "_check_fields",
    "_check_id_field",
    "_check_index_together",
    "_check_indexes",
    "_check_local_fields",
    "_check_long_column_names",
    "_check_m2m_through_same_relationship",
    "_check_managers",
    "_check_model",
    "_check_model_name_db_lookup_clashes",
    "_check_ordering",
    "_check_property_name_related_field_accessor_clashes",
    "_check_single_primary_key",
    "_check_swappable",
    "_check_unique_together",
    "_do_insert",
    "_do_update",
    "_get_FIELD_display",
    "_get_expr_references",
    "_get_field_value_map",
    "_get_next_or_previous_by_FIELD",
    "_get_next_or_previous_in_order",
    "_get_pk_val",
    "_get_session_auth_hash",
    "_get_unique_checks",
    "_meta",
    "_password",
    "_perform_date_checks",
    "_perform_unique_checks",
    "_prepare_related_fields_for_save",
    "_save_parents",
    "_save_table",
    "_set_pk_val",
    "_state",
    "_validate_force_insert",
    "acheck_password",
    "adelete",
    "arefresh_from_db",
    "asave",
    "check",
    "check_password",
    "clean",
    "clean_fields",
    "date_error_message",
    "date_joined",
    "delete",
    "email",
    "email_user",
    "first_name",
    "from_db",
    "full_clean",
    "get_all_permissions",
    "get_constraints",
    "get_deferred_fields",
    "get_email_field_name",
    "get_full_name",
    "get_group_permissions",
    "get_next_by_date_joined",
    "get_previous_by_date_joined",
    "get_session_auth_fallback_hash",
    "get_session_auth_hash",
    "get_short_name",
    "get_user_permissions",
    "get_username",
    "groups",
    "has_module_perms",
    "has_perm",
    "has_perms",
    "has_usable_password",
    "id",
    "is_active",
    "is_anonymous",
    "is_authenticated",
    "is_staff",
    "is_superuser",
    "last_login",
    "last_name",
    "logentry_set",
    "messages_i_sent",
    "messages_person_got",
    "natural_key",
    "normalize_username",
    "objects",
    "password",
    "pk",
    "prepare_database_save",
    "refresh_from_db",
    "save",
    "save_base",
    "serializable_value",
    "set_password",
    "set_unusable_password",
    "unique_error_message",
    "user_permissions",
    "userchannel_set",
    "username",
    "username_validator",
    "validate_constraints",
    "validate_unique",
]
