# Generated by Django 5.0 on 2026-04-27 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="from_who",
        ),
        migrations.AddField(
            model_name="message",
            name="me",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_i_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="to_who",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_person_got",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
