# Generated by Django 5.0 on 2026-04-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_userchannel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="to_who",
            new_name="reciever",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="me",
            new_name="sender",
        ),
    ]
